<?php

namespace Proxies\__CG__\AuthentBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \AuthentBundle\Entity\Cours implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idCours', 'desc', 'design', 'section', 'membre', 'chaps');
        }

        return array('__isInitialized__', 'idCours', 'desc', 'design', 'section', 'membre', 'chaps');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cours $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdCours()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdCours();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCours', array());

        return parent::getIdCours();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesc($desc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesc', array($desc));

        return parent::setDesc($desc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesc', array());

        return parent::getDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesign($design)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesign', array($design));

        return parent::setDesign($design);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesign()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesign', array());

        return parent::getDesign();
    }

    /**
     * {@inheritDoc}
     */
    public function setSection($section)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSection', array($section));

        return parent::setSection($section);
    }

    /**
     * {@inheritDoc}
     */
    public function getSection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSection', array());

        return parent::getSection();
    }

    /**
     * {@inheritDoc}
     */
    public function setMembre(\AuthentBundle\Entity\Membre $membre = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMembre', array($membre));

        return parent::setMembre($membre);
    }

    /**
     * {@inheritDoc}
     */
    public function getMembre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMembre', array());

        return parent::getMembre();
    }

    /**
     * {@inheritDoc}
     */
    public function addChap(\AuthentBundle\Entity\Chapitre $chaps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addChap', array($chaps));

        return parent::addChap($chaps);
    }

    /**
     * {@inheritDoc}
     */
    public function removeChap(\AuthentBundle\Entity\Chapitre $chaps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeChap', array($chaps));

        return parent::removeChap($chaps);
    }

    /**
     * {@inheritDoc}
     */
    public function getChaps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChaps', array());

        return parent::getChaps();
    }

}
